// <auto-generated />
using System;
using MegaCasting2022.DBLib.Class;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MegaCasting2022.DBLib.Migrations
{
    [DbContext(typeof(MegaCastingSymfonyContext))]
    [Migration("20230415150801_NewMigration")]
    partial class NewMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CiviliteOffreCasting", b =>
                {
                    b.Property<int>("IdentifiantCivilite")
                        .HasColumnType("int");

                    b.Property<int>("IdentifiantOffreCasting")
                        .HasColumnType("int");

                    b.HasKey("IdentifiantCivilite", "IdentifiantOffreCasting")
                        .HasName("PK__Civilite__0ECB1DAEFBB8978A");

                    b.HasIndex(new[] { "IdentifiantOffreCasting" }, "IDX_5CC7CA8DB196B681");

                    b.HasIndex(new[] { "IdentifiantCivilite" }, "IDX_5CC7CA8DCDCDB2D5");

                    b.ToTable("CiviliteOffreCasting", (string)null);
                });

            modelBuilder.Entity("MegaCasting2022.DBLib.Class.Civilite", b =>
                {
                    b.Property<int>("Identifiant")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Identifiant"), 1L, 1);

                    b.Property<string>("LibelLong")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("LibelShort")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Identifiant")
                        .HasName("PK__Civilite__DD380E4E01EAD5A6");

                    b.ToTable("Civilite", (string)null);
                });

            modelBuilder.Entity("MegaCasting2022.DBLib.Class.Client", b =>
                {
                    b.Property<int>("Identifiant")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Identifiant"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Login")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Password")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Telephone")
                        .HasColumnType("int");

                    b.Property<string>("Ville")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Identifiant")
                        .HasName("PK__Client__DD380E4E9D67E92C");

                    b.ToTable("Client", (string)null);
                });

            modelBuilder.Entity("MegaCasting2022.DBLib.Class.Conseil", b =>
                {
                    b.Property<int>("Identifiant")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Identifiant"), 1L, 1);

                    b.Property<string>("Contenu")
                        .IsRequired()
                        .HasMaxLength(3000)
                        .HasColumnType("nvarchar(3000)");

                    b.Property<string>("Libel")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Identifiant")
                        .HasName("PK__Conseil__DD380E4E157B2F5C");

                    b.ToTable("Conseil", (string)null);
                });

            modelBuilder.Entity("MegaCasting2022.DBLib.Class.DoctrineMigrationVersion", b =>
                {
                    b.Property<string>("Version")
                        .HasMaxLength(191)
                        .HasColumnType("nvarchar(191)")
                        .HasColumnName("version");

                    b.Property<DateTime?>("ExecutedAt")
                        .HasPrecision(6)
                        .HasColumnType("datetime2(6)")
                        .HasColumnName("executed_at");

                    b.Property<int?>("ExecutionTime")
                        .HasColumnType("int")
                        .HasColumnName("execution_time");

                    b.HasKey("Version")
                        .HasName("PK__doctrine__79B5C94C76A55E6D");

                    b.ToTable("doctrine_migration_versions", (string)null);
                });

            modelBuilder.Entity("MegaCasting2022.DBLib.Class.DomaineMetier", b =>
                {
                    b.Property<int>("Identifiant")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Identifiant"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(3000)
                        .HasColumnType("nvarchar(3000)");

                    b.Property<string>("Libel")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Identifiant")
                        .HasName("PK__DomaineM__DD380E4E999C6DDE");

                    b.ToTable("DomaineMetier", (string)null);
                });

            modelBuilder.Entity("MegaCasting2022.DBLib.Class.Interview", b =>
                {
                    b.Property<int>("Identifiant")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Identifiant"), 1L, 1);

                    b.Property<string>("Libel")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Identifiant")
                        .HasName("PK__Intervie__DD380E4E652293D6");

                    b.ToTable("Interview", (string)null);
                });

            modelBuilder.Entity("MegaCasting2022.DBLib.Class.Metier", b =>
                {
                    b.Property<int>("Identifiant")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Identifiant"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(3000)
                        .HasColumnType("nvarchar(3000)");

                    b.Property<int>("IdentifiantDomaineMetier")
                        .HasColumnType("int");

                    b.Property<string>("Libel")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Identifiant")
                        .HasName("PK__Metier__DD380E4E094284A5");

                    b.HasIndex(new[] { "IdentifiantDomaineMetier" }, "IDX_560C08BAE52D612A");

                    b.ToTable("Metier", (string)null);
                });

            modelBuilder.Entity("MegaCasting2022.DBLib.Class.OffreCasting", b =>
                {
                    b.Property<int>("Identifiant")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Identifiant"), 1L, 1);

                    b.Property<int>("IdentifiantClient")
                        .HasColumnType("int");

                    b.Property<int>("IdentifiantTypeContrat")
                        .HasColumnType("int");

                    b.Property<string>("Libel")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Localisation")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Nivurgence")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("nivurgence");

                    b.Property<DateTime>("OffreDateEnd")
                        .HasPrecision(6)
                        .HasColumnType("datetime2(6)");

                    b.Property<DateTime>("OffreDateStart")
                        .HasPrecision(6)
                        .HasColumnType("datetime2(6)");

                    b.Property<DateTime>("ParutionDateTime")
                        .HasPrecision(6)
                        .HasColumnType("datetime2(6)");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(3000)
                        .HasColumnType("nvarchar(3000)");

                    b.Property<bool?>("Sponso")
                        .HasColumnType("bit")
                        .HasColumnName("sponso");

                    b.HasKey("Identifiant")
                        .HasName("PK__OffreCas__DD380E4E203ACBC3");

                    b.HasIndex(new[] { "IdentifiantTypeContrat" }, "IDX_982EDF9C9251261A");

                    b.HasIndex(new[] { "IdentifiantClient" }, "IDX_982EDF9C93C1B089");

                    b.ToTable("OffreCasting", (string)null);
                });

            modelBuilder.Entity("MegaCasting2022.DBLib.Class.Pack", b =>
                {
                    b.Property<int>("Identifiant")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Identifiant"), 1L, 1);

                    b.Property<string>("Libel")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("NombreOffre")
                        .HasColumnType("int");

                    b.Property<int>("Tarif")
                        .HasColumnType("int");

                    b.HasKey("Identifiant")
                        .HasName("PK__Pack__DD380E4E21F50E1A");

                    b.ToTable("Pack", (string)null);
                });

            modelBuilder.Entity("MegaCasting2022.DBLib.Class.PartenaireDiffusion", b =>
                {
                    b.Property<int>("Identifiant")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Identifiant"), 1L, 1);

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Identifiant")
                        .HasName("PK__Partenai__DD380E4EC3719D87");

                    b.ToTable("PartenaireDiffusion", (string)null);
                });

            modelBuilder.Entity("MegaCasting2022.DBLib.Class.TypeContrat", b =>
                {
                    b.Property<int>("Identifiant")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Identifiant"), 1L, 1);

                    b.Property<string>("Libel")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Identifiant")
                        .HasName("PK__TypeCont__DD380E4E12219398");

                    b.ToTable("TypeContrat", (string)null);
                });

            modelBuilder.Entity("MegaCasting2022.DBLib.Class.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)")
                        .HasColumnName("email");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit")
                        .HasColumnName("is_verified");

                    b.Property<string>("Nom")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("nom");

                    b.Property<string>("Numtel")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("numtel");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("password");

                    b.Property<string>("Roles")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("roles")
                        .HasComment("(DC2Type:json)");

                    b.Property<string>("Ville")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ville");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Email" }, "UNIQ_8D93D649E7927C74")
                        .IsUnique()
                        .HasFilter("([email] IS NOT NULL)");

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("MetierOffreCasting", b =>
                {
                    b.Property<int>("IdentifiantMetier")
                        .HasColumnType("int");

                    b.Property<int>("IdentifiantOffreCasting")
                        .HasColumnType("int");

                    b.HasKey("IdentifiantMetier", "IdentifiantOffreCasting")
                        .HasName("PK__MetierOf__45F38DB504ABBE02");

                    b.HasIndex(new[] { "IdentifiantMetier" }, "IDX_A740572E525B950");

                    b.HasIndex(new[] { "IdentifiantOffreCasting" }, "IDX_A740572EB196B681");

                    b.ToTable("MetierOffreCasting", (string)null);
                });

            modelBuilder.Entity("CiviliteOffreCasting", b =>
                {
                    b.HasOne("MegaCasting2022.DBLib.Class.OffreCasting", null)
                        .WithMany()
                        .HasForeignKey("IdentifiantCivilite")
                        .IsRequired()
                        .HasConstraintName("FK_5CC7CA8DCDCDB2D5");

                    b.HasOne("MegaCasting2022.DBLib.Class.Civilite", null)
                        .WithMany()
                        .HasForeignKey("IdentifiantOffreCasting")
                        .IsRequired()
                        .HasConstraintName("FK_5CC7CA8DB196B681");
                });

            modelBuilder.Entity("MegaCasting2022.DBLib.Class.Metier", b =>
                {
                    b.HasOne("MegaCasting2022.DBLib.Class.DomaineMetier", "IdentifiantDomaineMetierNavigation")
                        .WithMany("Metiers")
                        .HasForeignKey("IdentifiantDomaineMetier")
                        .IsRequired()
                        .HasConstraintName("FK_560C08BAE52D612A");

                    b.Navigation("IdentifiantDomaineMetierNavigation");
                });

            modelBuilder.Entity("MegaCasting2022.DBLib.Class.OffreCasting", b =>
                {
                    b.HasOne("MegaCasting2022.DBLib.Class.Client", "IdentifiantClientNavigation")
                        .WithMany("OffreCastings")
                        .HasForeignKey("IdentifiantClient")
                        .IsRequired()
                        .HasConstraintName("FK_982EDF9C93C1B089");

                    b.HasOne("MegaCasting2022.DBLib.Class.TypeContrat", "IdentifiantTypeContratNavigation")
                        .WithMany("OffreCastings")
                        .HasForeignKey("IdentifiantTypeContrat")
                        .IsRequired()
                        .HasConstraintName("FK_982EDF9C9251261A");

                    b.Navigation("IdentifiantClientNavigation");

                    b.Navigation("IdentifiantTypeContratNavigation");
                });

            modelBuilder.Entity("MetierOffreCasting", b =>
                {
                    b.HasOne("MegaCasting2022.DBLib.Class.OffreCasting", null)
                        .WithMany()
                        .HasForeignKey("IdentifiantMetier")
                        .IsRequired()
                        .HasConstraintName("FK_A740572E525B950");

                    b.HasOne("MegaCasting2022.DBLib.Class.Metier", null)
                        .WithMany()
                        .HasForeignKey("IdentifiantOffreCasting")
                        .IsRequired()
                        .HasConstraintName("FK_A740572EB196B681");
                });

            modelBuilder.Entity("MegaCasting2022.DBLib.Class.Client", b =>
                {
                    b.Navigation("OffreCastings");
                });

            modelBuilder.Entity("MegaCasting2022.DBLib.Class.DomaineMetier", b =>
                {
                    b.Navigation("Metiers");
                });

            modelBuilder.Entity("MegaCasting2022.DBLib.Class.TypeContrat", b =>
                {
                    b.Navigation("OffreCastings");
                });
#pragma warning restore 612, 618
        }
    }
}
